### ISSUE TITLE
Scope problem

### ISSUE THREAD

**Issue by keesschouten** [Q42/Orchard-DbTranslations#24]
Many of my translations gets a scope in the culture.Translations list but for some of them in the method GetLocalizedString the scope is null so they don't match! Is this a bug in the translations module or is my po file corrupted or the database? thanks (alvast bedankt)

**Comment by keesschouten** [comment]
I've made a quick fix for this problem:

public string GetLocalizedString(string scope, string text, string cultureName)
 {
            var culture = LoadCulture(cultureName);

```
        string scopedKey = !string.IsNullOrWhiteSpace(scope) ? (scope + "|" + text).ToLowerInvariant() : text.ToLowerInvariant();
        if (culture.Translations.ContainsKey(scopedKey))
        {
            return culture.Translations[scopedKey];
        }

        string genericKey = ("|" + text).ToLowerInvariant();
        if (culture.Translations.ContainsKey(genericKey))
            return culture.Translations[genericKey];

        string retVal = GetParentTranslation(scope, text, cultureName);

        if (retVal == text && culture.Translations.Any(s => s.Key.Contains("|"+scopedKey)))
            retVal = culture.Translations.FirstOrDefault(s => s.Key.Contains("|" + scopedKey)).Value;

        return retVal;
    }
```

**Comment by lukasvan3l** [comment]
I entered your fix in the source and will deploy asap!
