### ISSUE TITLE
An unhandled exception in admin controller method ImportCurrentPos

### ISSUE THREAD

**Issue by keesschouten** [Q42/Orchard-DbTranslations#25]
First i had to cultures when i downloaded the po files from the orchard gallery automatically. Afterwards I removed one culture (en-US) because i not needed it anymore. Now i get a error in the method:  AdminController in method ImportCurrentPos line:
throw new Exception("Cannot find culture in path " + file);

I think this error can be ignored and not being trown.
Hopefully you can fix it :) 
Thanks (alvast bedankt ;) )

**Comment by lukasvan3l** [comment]
Now logging instead of throwing!
